openapi: "3.0.3"
info:
  title: Vajeh API
  description: Vajeh API
  version: "1.0.0"
servers:
  - url: "https://${api_url}"
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                type: object
      security:
        - auth: [ ${ auth_scopes } ]
      x-amazon-apigateway-integration:
        uri: "${lambda_identity_arn}"
        passthroughBehavior: "when_no_match"
        payloadFormatVersion: "1.0"
        httpMethod: "POST"
        timeoutInMillis: 30000
        type: "AWS_PROXY"

components:
  securitySchemes:
    auth:
      type: "oauth2"
      flows: { }
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization"
        jwtConfiguration:
          audience: [ ${ auth_audience } ]
          issuer: "${auth_issuer}"
        type: "jwt"
x-amazon-apigateway-importexport-version: "1.0"
