openapi: 3.0.3
info:
  title: Vajeh API
  description: Vajeh API
  version: 1.0.0
servers:
  - url: "https://${api_url}"
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: A paged array of pets
          content:
            text/plain:
              schema:
                type: string
      x-amazon-apigateway-integration:
        uri: "${lambda_identity_arn}"
        passthroughBehavior: "when_no_match"
        payloadFormatVersion: "1.0"
        httpMethod: "POST"
        timeoutInMillis: 30000
        type: "AWS_PROXY"
