name: 'Pull Request'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-pr:
    name: Deploy PR
    runs-on: ubuntu-latest
    environment: dev
    env:
      TF_PLUGIN_CACHE_DIR: "${GITHUB_WORKSPACE}/plugin-cache"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache terraform
        uses: actions/cache@v3
        with:
          key: terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          path: "${{ env.TF_PLUGIN_CACHE_DIR }}"

      - name: Install invoke
        run: pip install invoke

      - name: Create .env file
        run: |
          echo "cache dir"
          echo $TF_PLUGIN_CACHE_DIR

          cat << EOF > .env
          PROJECT=vajeh-api
          ENVIRONMENT=dev
          WORKSPACE=pr_${{ github.event.pull_request.number }}
          TERRAFORM_DIR=terraform
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          EOF

      - name: Deploy PR
        run: |
          invoke init
          invoke apply

      - name: check
        run: ls $TF_PLUGIN_CACHE_DIR

