name: 'Pull Request'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-pr:
    name: Deploy PR
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config Terraform plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: Install invoke
        run: pip install invoke

      - name: Create .env file
        run: |
          cat << EOF > .env
          PROJECT=vajeh-api
          ENVIRONMENT=dev
          WORKSPACE=pr_${{ github.event.pull_request.number }}
          TERRAFORM_DIR=terraform
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

      - name: Deploy PR
        run: |
          invoke init
          invoke apply

      - name: check
        run: |
          cat ~/.terraformrc
          ls ~
          ls ~/.terraform.d/plugin-cache


