name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache terraform
        uses: actions/cache@v3
        with:
          key: terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}
          path: terraform/.terraform

      - name: Install invoke
        run: pip install invoke

      - name: Create .env file
        run: |
          cat << EOF > .env
          PROJECT=vajeh-api
          ENVIRONMENT=dev
          WORKSPACE=dev
          TERRAFORM_DIR=terraform
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          EOF

      - name: Deploy dev
        run: |
          invoke init
          invoke apply
