name: 'Pull Request'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-pr:
    name: Deploy PR
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install invoke
        run: pip install invoke

      - name: Deploy PR
        env:
          WORKSPACE: pr-${{ github.event.pull_request.number }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          touch .env
          invoke init
          invoke apply
