name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install invoke
        run: pip install invoke

      - name: Deploy dev
        env:
          PROJECT: vajeh-api
          WORKSPACE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          invoke init
          invoke apply
