name: Destroy PR deployment
on:
  pull_request:
    types: [closed]

jobs:
  destroy-pr-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install invoke
        run: pip install invoke

      - name: Destroy PR
        env:
          WORKSPACE: pr-${{ github.event.pull_request.number }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          touch .env
          invoke init
          invoke destroy --no-dryrun

